shiny-aqua = [dark-white].
muted-blue = [vibrant-lavender, dotted-silver, dotted-silver, dotted-silver, dotted-silver, dim-indigo, dim-indigo].
drab-gray = [mirrored-white, mirrored-white, mirrored-white, mirrored-white, mirrored-white, light-green, shiny-lavender, shiny-lavender, shiny-lavender, shiny-lavender, shiny-lavender, faded-aqua, faded-aqua, faded-aqua, faded-aqua, faded-aqua].
muted-indigo = [muted-chartreuse, muted-chartreuse, muted-chartreuse, muted-chartreuse, dotted-teal, dotted-teal].
drab-white = [dull-fuchsia, dull-fuchsia, vibrant-bronze].
dim-lavender = [muted-tan, muted-tan, muted-tan, muted-tan].
dotted-tomato = [mirrored-lime, vibrant-white, vibrant-white].
clear-orange = [clear-violet, clear-violet, clear-violet, clear-violet, clear-violet, dull-beige, dull-beige, dark-chartreuse, dark-chartreuse].
bright-lime = [no-other].
striped-brown = [bright-orange, bright-orange, bright-orange].
vibrant-green = [shiny-fuchsia, shiny-fuchsia, shiny-fuchsia].
plaid-tomato = [faded-chartreuse, faded-chartreuse, faded-chartreuse, wavy-salmon, wavy-salmon, faded-white, mirrored-maroon, mirrored-maroon, mirrored-maroon].
drab-beige = [shiny-bronze, shiny-bronze, pale-violet, pale-violet, pale-violet, pale-violet, bright-tomato, bright-tomato, bright-tomato, pale-red, pale-red, pale-red, pale-red].
posh-green = [dull-lavender, dull-lavender, clear-plum, clear-plum, clear-plum, clear-plum, dark-gray, dark-gray].
dull-maroon = [dull-magenta, dull-magenta, dull-magenta, dull-tan, faded-cyan, dull-silver, dull-silver, dull-silver, dull-silver, dull-silver].
faded-crimson = [muted-purple, muted-purple, dotted-olive, dotted-olive, dotted-olive, dotted-olive, drab-silver, drab-silver, drab-silver, drab-silver, drab-silver].
wavy-bronze = [dark-orange, dark-orange, dark-orange, dark-brown, dark-brown, bright-silver, bright-silver, bright-silver, bright-silver, bright-silver].
dark-turquoise = [dull-plum, dull-plum, dull-plum, dull-plum, dull-plum].
dull-lavender = [dotted-maroon, dotted-maroon, dotted-maroon, dotted-maroon, muted-brown, muted-brown, muted-brown, drab-black, drab-black, drab-black, drab-black, dull-cyan, dull-cyan, dull-cyan, dull-cyan].
dotted-plum = [shiny-bronze, clear-brown, clear-brown, clear-brown, muted-indigo, muted-indigo, muted-indigo].
dull-white = [clear-tan, clear-tan, clear-tan, shiny-gold, shiny-gold, shiny-gold, shiny-gold, shiny-gold, drab-crimson, drab-crimson].
dull-teal = [bright-tomato, bright-tomato].
shiny-crimson = [light-green, light-green, light-green, striped-brown, striped-brown, striped-brown, striped-brown, striped-brown, faded-fuchsia, faded-fuchsia, faded-fuchsia].
wavy-brown = [drab-crimson, wavy-indigo, wavy-indigo].
dark-tan = [faded-gray, faded-gray, shiny-salmon, shiny-salmon, shiny-salmon, shiny-salmon].
shiny-red = [dull-chartreuse, dull-chartreuse, dull-chartreuse, dull-chartreuse, pale-tomato, pale-tomato, pale-tomato, pale-tomato, pale-tomato].
bright-orange = [no-other].
wavy-yellow = [light-indigo, light-indigo, light-indigo, light-indigo, light-indigo, dark-gray, dark-gray, dark-gray, dark-gray, dark-gray, plaid-indigo, plaid-indigo, plaid-indigo, plaid-indigo, plaid-indigo, faded-red, faded-red, faded-red, faded-red].
faded-bronze = [faded-cyan, faded-cyan, faded-cyan, faded-cyan, shiny-beige, shiny-beige, shiny-beige, shiny-beige, shiny-beige, muted-red, muted-red, muted-red, muted-red, muted-red].
dull-bronze = [mirrored-beige, muted-violet, muted-violet, muted-violet, muted-violet, muted-violet, wavy-lime].
dark-lime = [drab-maroon, drab-maroon, bright-indigo, bright-indigo, bright-indigo, bright-indigo, bright-indigo, shiny-black, shiny-black, shiny-black, shiny-black, dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise].
drab-red = [bright-red, bright-red, bright-red, bright-red, bright-red, vibrant-brown, vibrant-brown].
dotted-salmon = [vibrant-turquoise, vibrant-turquoise, vibrant-turquoise, dull-beige, dull-beige, light-turquoise, light-turquoise, light-turquoise].
dull-gray = [striped-green, striped-green, striped-green, wavy-coral, wavy-coral, wavy-coral, dark-gray, light-indigo, light-indigo].
faded-black = [muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia, wavy-coral, wavy-coral, wavy-coral, wavy-coral, drab-tomato].
muted-magenta = [posh-chartreuse, posh-chartreuse, pale-violet, pale-violet, pale-violet, pale-violet].
light-tan = [posh-turquoise, posh-turquoise, vibrant-white, vibrant-white, vibrant-white, light-black].
dark-blue = [plaid-indigo, plaid-indigo, plaid-indigo, posh-black, posh-black].
dull-indigo = [light-gray, light-gray, light-gray, light-gray, dotted-tan, dotted-tan, dotted-tan, dull-coral, dull-coral, dull-coral, dull-coral].
dim-fuchsia = [vibrant-yellow, vibrant-yellow, vibrant-yellow, mirrored-cyan, mirrored-cyan, mirrored-cyan, mirrored-brown, mirrored-brown, mirrored-brown, mirrored-brown].
shiny-beige = [dull-silver, dull-silver, bright-lime, bright-lime, bright-lime, dull-magenta, dull-magenta, dull-magenta, dull-magenta, dull-magenta].
light-cyan = [vibrant-violet, vibrant-violet, vibrant-violet, mirrored-tomato, mirrored-tomato, vibrant-coral, vibrant-coral, mirrored-silver, mirrored-silver, mirrored-silver, mirrored-silver].
clear-turquoise = [drab-tomato, drab-tomato, drab-tomato, drab-tomato, shiny-gold, shiny-gold, shiny-gold, drab-gold, drab-gold, drab-gold, drab-gold].
pale-teal = [wavy-maroon, wavy-maroon, dotted-olive, dotted-olive, shiny-white, shiny-white, shiny-white, shiny-white, drab-turquoise, drab-turquoise].
dark-purple = [wavy-indigo, bright-black, bright-black, bright-black, dotted-teal, dotted-teal, dotted-teal].
bright-white = [wavy-red, wavy-red, wavy-red, wavy-red, wavy-red, mirrored-cyan, mirrored-cyan, drab-green, drab-green, drab-green].
mirrored-aqua = [faded-violet, dotted-purple, dotted-purple, dotted-purple, dotted-purple, dotted-purple].
shiny-lime = [dark-aqua, dark-aqua, dark-aqua, dark-aqua].
pale-bronze = [clear-crimson].
vibrant-white = [plaid-lavender, plaid-lavender, plaid-lavender, plaid-lavender, plaid-lavender, drab-red, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown].
plaid-tan = [dim-crimson, dim-crimson, dim-crimson, dim-crimson, dim-crimson].
posh-olive = [bright-red, bright-red, bright-red].
plaid-brown = [vibrant-turquoise, vibrant-turquoise, vibrant-turquoise, vibrant-turquoise, vibrant-turquoise].
mirrored-tomato = [dotted-chartreuse, dotted-chartreuse, light-aqua, light-aqua, light-aqua, posh-beige, posh-beige, posh-beige].
plaid-blue = [striped-green, striped-green, striped-green, striped-green, striped-green, plaid-purple, muted-gold, muted-gold, muted-gold, muted-gold].
shiny-tan = [striped-coral, striped-coral, striped-coral, striped-coral, striped-coral, dull-brown].
shiny-gold = [dull-magenta, dark-white, dark-white, dark-white, dark-white, dark-white, faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise].
dull-salmon = [plaid-gold, plaid-gold, light-indigo, light-indigo].
striped-tomato = [striped-tan, striped-tan, light-blue, light-blue, light-blue, light-blue, drab-tan, drab-tan, drab-tan, drab-tan].
drab-tomato = [dim-teal, dim-teal, dim-teal, striped-yellow, striped-yellow, striped-yellow, striped-yellow, bright-red, bright-red, bright-red].
faded-olive = [drab-plum, pale-aqua, light-blue, light-blue, light-blue].
dotted-indigo = [clear-tomato, clear-tomato].
dark-white = [light-aqua, light-aqua, light-aqua, light-aqua, light-aqua, dim-teal, dim-teal, muted-fuchsia, muted-fuchsia, light-purple, light-purple, light-purple, light-purple, light-purple].
dull-orange = [pale-gold, pale-gold, pale-gold, pale-gold, posh-brown, posh-brown, posh-brown, posh-brown, posh-brown, mirrored-brown, mirrored-brown, dark-bronze, dark-bronze, dark-bronze].
bright-maroon = [mirrored-yellow, light-teal, light-teal, light-teal, light-teal].
bright-silver = [vibrant-coral, dim-teal, dim-teal, dim-teal, light-purple, light-purple, light-purple, light-purple, light-purple].
muted-olive = [plaid-orange, plaid-orange, plaid-orange, plaid-orange, plaid-orange, muted-magenta].
dull-silver = [no-other].
pale-maroon = [pale-bronze, pale-bronze].
light-gray = [vibrant-yellow, vibrant-yellow, vibrant-yellow, vibrant-yellow, pale-red, pale-red].
drab-teal = [light-crimson, light-crimson, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-tan, vibrant-tan, vibrant-tan].
bright-gold = [wavy-red, wavy-coral, wavy-coral, wavy-coral, wavy-coral, wavy-coral].
plaid-chartreuse = [dim-coral, dim-coral, drab-silver, drab-silver, drab-silver, drab-silver, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, light-purple, light-purple, light-purple].
clear-blue = [pale-tomato, pale-tomato, dull-gold, dull-gold, dull-gold, dull-gold, dim-fuchsia, dim-fuchsia, dim-fuchsia, dim-fuchsia, pale-coral, pale-coral, pale-coral, pale-coral].
vibrant-purple = [faded-orange, faded-orange, faded-orange, faded-orange, faded-orange].
plaid-aqua = [muted-cyan, muted-cyan, muted-cyan, wavy-gray, wavy-gray, drab-green, drab-green, drab-green, drab-green, pale-beige, pale-beige, pale-beige, pale-beige].
muted-lime = [muted-tan].
faded-coral = [drab-turquoise, drab-turquoise, drab-turquoise, shiny-plum, mirrored-green, mirrored-green, mirrored-green, mirrored-green, mirrored-green, clear-white, clear-white, clear-white, clear-white, clear-white].
vibrant-lime = [posh-coral, posh-coral, posh-coral, posh-coral, posh-coral].
faded-green = [pale-orange, pale-orange, pale-orange, dull-turquoise, dull-turquoise, dull-turquoise, dull-turquoise, dull-turquoise, mirrored-crimson].
mirrored-gray = [dim-indigo, dim-indigo, dim-indigo, dim-indigo, dim-indigo].
wavy-maroon = [mirrored-bronze, mirrored-bronze, mirrored-bronze, mirrored-bronze, striped-olive, dull-salmon, dull-salmon, shiny-crimson, shiny-crimson, shiny-crimson].
dark-violet = [light-purple, light-purple].
dark-green = [dim-cyan, dim-cyan].
pale-black = [mirrored-gold].
bright-yellow = [vibrant-crimson, vibrant-crimson, plaid-lime, plaid-lime, plaid-lime, dotted-gold, dotted-gold].
muted-teal = [pale-violet, dull-silver, dull-silver, dull-silver, dull-silver].
dim-beige = [wavy-red, wavy-red, wavy-red, wavy-red, wavy-red].
muted-purple = [clear-cyan, clear-cyan, clear-cyan, clear-cyan].
plaid-fuchsia = [dark-coral, dark-coral, dark-coral].
plaid-bronze = [plaid-orange, plaid-orange, plaid-orange, plaid-orange, plaid-orange, drab-indigo, drab-indigo].
faded-indigo = [dark-chartreuse, dull-green, dull-green, dull-green, dull-green, mirrored-magenta].
posh-plum = [dark-chartreuse, dark-chartreuse, dark-chartreuse, dotted-turquoise, dotted-turquoise, dotted-turquoise, dull-maroon, dull-maroon, dull-maroon, dull-maroon, posh-bronze].
pale-gold = [striped-brown, striped-brown, striped-brown, striped-brown].
mirrored-chartreuse = [bright-silver, bright-silver, bright-silver, bright-silver, mirrored-tomato, mirrored-tomato, mirrored-tomato, wavy-orange, wavy-orange, wavy-orange, wavy-orange].
pale-orange = [posh-fuchsia, posh-fuchsia, clear-salmon, clear-salmon, bright-green, bright-green].
clear-brown = [light-lime, light-lime, light-lime, light-lime, bright-green, bright-green, bright-green, bright-green, pale-yellow, pale-yellow, pale-yellow, pale-yellow, pale-yellow, drab-cyan, drab-cyan].
shiny-plum = [vibrant-gray, vibrant-gray, vibrant-gray, vibrant-gray, vibrant-gray, bright-blue, bright-blue, bright-blue, dark-tomato, dark-tomato, dark-tomato, dark-tomato, dark-tomato].
wavy-white = [plaid-lime, plaid-lime, plaid-lime, plaid-lime, posh-maroon, posh-maroon, posh-maroon, posh-maroon, drab-lime, drab-lime, drab-lime, drab-lime, drab-lime, vibrant-crimson].
faded-red = [dull-coral, clear-cyan, clear-cyan, clear-cyan, clear-cyan, clear-cyan, plaid-chartreuse, plaid-chartreuse, plaid-chartreuse, plaid-chartreuse, plaid-orange, plaid-orange, plaid-orange].
plaid-red = [pale-blue, pale-blue, pale-blue, pale-blue, pale-blue, light-crimson, light-crimson, light-crimson, light-crimson, faded-fuchsia, faded-fuchsia, faded-fuchsia].
bright-cyan = [dark-white, dark-white, dark-white, light-crimson, light-crimson, bright-aqua].
muted-lavender = [light-green, striped-silver, striped-silver, striped-silver, striped-silver, posh-crimson, posh-crimson, posh-crimson].
wavy-crimson = [light-purple, bright-blue, bright-blue, bright-blue, bright-blue, dull-coral, dull-coral, wavy-beige].
faded-aqua = [muted-brown, muted-brown, muted-brown, muted-brown, muted-brown].
mirrored-fuchsia = [faded-beige, muted-gold, muted-gold, muted-gold].
dark-chartreuse = [bright-lime, bright-lime, bright-lime, bright-lime, bright-lime].
plaid-green = [mirrored-tan, mirrored-tan, mirrored-tan, mirrored-tan, mirrored-tomato, pale-indigo, pale-indigo, pale-indigo, pale-indigo, pale-indigo, mirrored-plum].
shiny-black = [plaid-chartreuse, plaid-chartreuse, plaid-chartreuse].
dotted-purple = [dim-teal, dim-teal].
faded-tan = [bright-fuchsia, bright-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, muted-fuchsia, mirrored-brown].
drab-brown = [striped-orange, dotted-tomato, dotted-tomato, dotted-tomato, dotted-tomato].
dull-olive = [striped-black, vibrant-magenta].
mirrored-plum = [clear-gold, pale-green, pale-green, pale-green, pale-green, pale-green].
dim-tomato = [drab-gold, drab-gold, drab-gold, drab-gold, shiny-aqua, shiny-aqua].
light-lavender = [muted-violet].
dim-gray = [light-purple, light-purple, light-purple, posh-crimson, faded-brown].
muted-aqua = [dull-beige, dull-beige, dull-beige, dull-beige, dull-red, dull-red, dull-red, dull-red].
faded-silver = [mirrored-cyan].
shiny-green = [dull-maroon, dull-maroon, dull-maroon, dull-maroon, dull-maroon].
muted-chartreuse = [clear-tan, clear-tan].
plaid-plum = [dotted-lime, clear-brown, clear-brown, clear-brown, clear-brown, dull-red, dull-red, dull-red, dull-red].
dotted-silver = [posh-coral].
dim-crimson = [faded-violet, faded-violet, faded-violet, faded-violet, striped-silver].
bright-brown = [bright-coral, posh-brown, posh-brown, posh-brown, drab-tan, drab-tan, drab-tan, drab-tan].
wavy-cyan = [clear-gold, clear-gold, clear-gold, mirrored-salmon, bright-fuchsia, bright-fuchsia, bright-fuchsia, light-bronze, light-bronze].
dull-violet = [striped-white, striped-white, striped-white, striped-white, striped-white, light-blue, light-blue, light-blue, light-blue, dim-black, dim-black, dim-black, dim-black].
vibrant-olive = [vibrant-coral, vibrant-coral].
bright-coral = [vibrant-tan, vibrant-tan, shiny-indigo, shiny-indigo, shiny-indigo, plaid-indigo, plaid-indigo].
dim-turquoise = [pale-violet].
striped-crimson = [faded-gray, faded-gray].
clear-green = [mirrored-olive, mirrored-olive, mirrored-olive, shiny-tomato, shiny-tomato, shiny-tomato].
faded-violet = [wavy-coral, wavy-coral, dull-tan, dull-tan, dull-silver, bright-orange].
pale-chartreuse = [shiny-crimson, shiny-crimson, shiny-crimson, shiny-crimson, clear-bronze, clear-bronze].
light-plum = [drab-bronze, drab-bronze, drab-bronze, bright-bronze, posh-yellow].
pale-tomato = [dim-teal, drab-cyan, drab-cyan, drab-cyan, drab-cyan, drab-cyan, muted-coral, muted-coral, muted-coral, dim-chartreuse, dim-chartreuse].
plaid-coral = [striped-tan, vibrant-cyan, vibrant-cyan, vibrant-cyan, light-beige, light-beige, light-beige, dotted-green, dotted-green].
bright-gray = [mirrored-teal, mirrored-teal, mirrored-teal, mirrored-teal, striped-brown, striped-brown, striped-brown, striped-brown, dim-green, clear-cyan, clear-cyan, clear-cyan, clear-cyan].
drab-fuchsia = [mirrored-salmon, mirrored-salmon, posh-orange, posh-orange, posh-orange, posh-orange, faded-crimson, faded-crimson, faded-crimson, pale-plum, pale-plum, pale-plum].
light-tomato = [dotted-gold, dotted-gold, dotted-bronze].
muted-violet = [light-chartreuse, light-chartreuse].
drab-tan = [light-green, light-green, bright-red, bright-red, bright-red, bright-red, bright-red, shiny-beige, shiny-beige, shiny-beige, shiny-beige].
drab-chartreuse = [drab-salmon, drab-salmon, dark-brown, dark-brown, clear-turquoise, clear-turquoise, clear-turquoise, clear-turquoise].
drab-violet = [faded-red, faded-red, faded-red, faded-red].
posh-cyan = [bright-violet, bright-violet, bright-violet, bright-violet].
posh-orange = [pale-plum, pale-plum, pale-plum, pale-plum, posh-aqua, posh-aqua, posh-aqua, posh-aqua, posh-aqua].
plaid-silver = [dotted-brown, drab-gold, drab-gold, drab-gold, clear-yellow, clear-yellow, clear-yellow, clear-yellow].
mirrored-silver = [shiny-beige, shiny-beige, shiny-beige, drab-silver].
faded-gray = [no-other].
wavy-tomato = [bright-brown, striped-red, striped-red, striped-red, vibrant-maroon, vibrant-maroon].
posh-violet = [dim-aqua, dim-aqua].
bright-blue = [light-lime, light-lime, light-lime, light-lime, light-lime, faded-violet, faded-violet, light-aqua, light-aqua, light-aqua, vibrant-coral, vibrant-coral, vibrant-coral, vibrant-coral].
dark-teal = [muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia].
striped-fuchsia = [wavy-turquoise, wavy-green, wavy-green, wavy-green, wavy-green, wavy-green, posh-gold, posh-gold, posh-gold, posh-gold].
posh-maroon = [dull-red, dull-red].
shiny-purple = [clear-tan, clear-tan].
wavy-lime = [dark-coral, dark-coral, shiny-gold].
wavy-silver = [dotted-white, dotted-white, dotted-white, dotted-white].
shiny-silver = [plaid-gold, plaid-gold, dim-green, dim-green, plaid-lime, plaid-lime, plaid-lime, plaid-lime, plaid-lime, dull-red, dull-red, dull-red].
wavy-red = [vibrant-brown, vibrant-brown, vibrant-brown, bright-indigo, bright-indigo, bright-indigo, bright-indigo].
dull-chartreuse = [dotted-lime, dotted-lime, dotted-lime, dotted-lime, bright-silver, bright-silver, dull-red, dull-red, dull-red, wavy-maroon, wavy-maroon, wavy-maroon, wavy-maroon].
vibrant-silver = [bright-fuchsia, drab-lavender, drab-lavender, drab-lavender, drab-olive, drab-olive, dotted-teal, dotted-teal, dotted-teal].
striped-gray = [plaid-orange, plaid-orange, plaid-orange, plaid-orange, plaid-orange, wavy-coral].
striped-green = [wavy-coral, wavy-coral, wavy-coral, wavy-coral, shiny-gold, shiny-gold, shiny-gold, shiny-gold, dark-brown, dark-brown, dark-brown, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown].
mirrored-violet = [dim-silver, dim-silver, dim-silver, posh-tomato, light-salmon].
dull-purple = [light-gray, wavy-yellow, wavy-yellow, wavy-yellow, wavy-salmon].
mirrored-beige = [dark-cyan, dark-cyan, dark-cyan, dark-cyan, dull-green, dull-green, dull-green, dull-green, dull-green].
posh-lime = [posh-chartreuse, posh-chartreuse, posh-chartreuse].
vibrant-tan = [dull-plum, dull-plum, striped-brown, vibrant-coral, vibrant-coral, vibrant-coral, vibrant-coral].
dotted-orange = [mirrored-olive, drab-silver, drab-silver, drab-silver, drab-silver, drab-silver].
clear-indigo = [light-lime, light-lime, light-lime, dull-coral, dull-coral, dull-coral, dull-coral].
pale-gray = [faded-black, dim-green, dim-green, dim-green, wavy-lavender, wavy-lavender, wavy-lavender, wavy-lavender, posh-brown, posh-brown].
posh-gold = [dark-tan, dark-tan, dark-tan, dark-tan, dark-tan, dotted-olive, dotted-olive, dark-aqua, dark-aqua, dark-aqua, dark-aqua, dark-aqua].
striped-chartreuse = [dull-magenta, dull-magenta, posh-tomato].
mirrored-bronze = [faded-fuchsia, faded-fuchsia].
clear-salmon = [posh-bronze, posh-bronze, posh-bronze, posh-bronze, clear-plum, clear-plum, clear-plum, clear-plum, clear-plum, dull-blue, dull-blue, dull-blue, dull-blue, dull-blue].
posh-purple = [dim-gray, dim-gray, dim-gray, dim-gray, dim-gray, faded-brown, faded-brown, faded-brown].
faded-lime = [dim-turquoise, dim-turquoise, dim-turquoise, dim-turquoise, dim-turquoise, dark-indigo, dark-indigo, dark-indigo, vibrant-gray, vibrant-gray, muted-silver].
wavy-beige = [dark-bronze, dull-plum, dull-plum, dull-plum, dull-plum, mirrored-silver, mirrored-silver, mirrored-silver, mirrored-silver].
clear-yellow = [vibrant-teal, vibrant-teal].
vibrant-plum = [muted-chartreuse, muted-chartreuse, muted-chartreuse, muted-chartreuse, posh-silver, posh-silver, posh-silver, posh-silver].
striped-yellow = [dull-maroon, dull-maroon, bright-red, bright-red, bright-red, bright-red, bright-red, posh-chartreuse, posh-chartreuse].
dark-coral = [dull-tan, dull-tan, dull-tan].
dull-magenta = [no-other].
dark-gold = [dotted-indigo, shiny-teal, shiny-teal, shiny-teal, shiny-teal, dotted-silver, dotted-silver, dotted-silver, dotted-silver].
dim-tan = [striped-lavender, shiny-tomato].
muted-maroon = [dull-salmon, dull-salmon, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, bright-aqua, bright-aqua, bright-aqua, faded-indigo, faded-indigo].
vibrant-tomato = [dark-silver, dark-silver, plaid-purple, plaid-purple, plaid-purple].
dotted-lime = [shiny-crimson, shiny-crimson, shiny-crimson, pale-yellow, pale-yellow].
muted-fuchsia = [dull-tan].
bright-tan = [pale-gold, pale-gold, pale-gold, pale-gold, pale-gold, drab-teal, drab-teal, drab-teal, drab-teal, drab-teal, light-blue, light-blue].
dark-crimson = [shiny-orange, shiny-orange, shiny-orange, shiny-orange, faded-purple, faded-purple, faded-purple, bright-white, bright-white, bright-white].
striped-tan = [dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, drab-lime, drab-lime, drab-lime, drab-lime, dim-teal, dim-teal, dim-teal, dim-teal, dim-teal].
posh-fuchsia = [dotted-olive, dotted-olive, mirrored-beige, mirrored-beige, shiny-bronze, shiny-bronze, shiny-bronze].
pale-silver = [vibrant-lavender, vibrant-lavender, vibrant-lavender, vibrant-lavender, clear-beige, clear-beige, clear-beige, clear-beige, striped-gold, striped-gold, striped-gold, striped-gold].
posh-aqua = [drab-lime, drab-lime, drab-lime, drab-lime, dull-tan, dull-tan, dull-tan, dull-tan, vibrant-tan, vibrant-tan, vibrant-tan, vibrant-tan, vibrant-tan].
plaid-salmon = [dim-coral, dim-coral, dim-coral, dim-coral, dim-coral, wavy-bronze, wavy-bronze].
mirrored-orange = [vibrant-gray, vibrant-gray, vibrant-gray, vibrant-gray].
dim-yellow = [pale-tan, pale-tan, pale-tan, pale-tan, pale-tan, dark-black, dark-black, dark-black, dark-black].
dotted-coral = [dotted-chartreuse, dotted-chartreuse, dotted-chartreuse, dotted-chartreuse, bright-red, bright-red, vibrant-white, vibrant-brown].
muted-crimson = [striped-orange, striped-orange, striped-orange, striped-orange, pale-yellow, pale-yellow, pale-yellow, pale-yellow, pale-yellow, posh-blue, posh-blue, posh-blue, muted-red].
striped-lavender = [striped-brown, striped-brown, striped-brown].
striped-maroon = [shiny-yellow, shiny-yellow].
vibrant-blue = [faded-cyan, faded-cyan, faded-cyan, shiny-lime, dark-tomato, dark-tomato, dark-tomato].
pale-lavender = [plaid-magenta, plaid-magenta, plaid-magenta, plaid-magenta, striped-blue, striped-blue, striped-blue, striped-blue].
dull-tan = [shiny-indigo, shiny-indigo, shiny-indigo, shiny-indigo, light-purple, light-purple, faded-cyan, faded-cyan, faded-cyan, faded-cyan].
dotted-beige = [drab-indigo, drab-indigo, drab-indigo].
light-indigo = [faded-cyan, bright-aqua, bright-aqua, bright-aqua, bright-aqua, bright-aqua, shiny-indigo].
vibrant-crimson = [dotted-fuchsia, dotted-fuchsia, dotted-fuchsia, dotted-fuchsia].
wavy-blue = [wavy-teal, wavy-teal, wavy-teal, wavy-teal, dull-blue].
vibrant-chartreuse = [striped-orange, striped-orange, striped-orange, striped-orange].
vibrant-cyan = [wavy-coral, wavy-coral, wavy-coral, wavy-coral, wavy-coral].
faded-brown = [faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise].
faded-magenta = [dull-indigo, plaid-aqua, plaid-aqua, plaid-aqua, plaid-aqua, dim-crimson, dim-crimson, dim-crimson, dim-crimson].
mirrored-coral = [drab-crimson, drab-crimson, drab-crimson, drab-crimson, light-salmon, light-salmon, clear-indigo, clear-indigo].
faded-cyan = [no-other].
dark-brown = [light-purple, light-purple, light-purple, light-purple, light-purple].
wavy-violet = [dull-coral, dull-coral, dull-coral, bright-aqua, shiny-lavender, shiny-lavender, shiny-lavender].
posh-tomato = [vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, mirrored-teal, mirrored-teal, mirrored-teal, mirrored-teal].
pale-crimson = [plaid-orange, dark-violet, plaid-lavender, plaid-lavender, plaid-lavender].
dark-fuchsia = [plaid-beige, plaid-beige, plaid-beige, plaid-beige, plaid-chartreuse, plaid-chartreuse].
plaid-magenta = [clear-lavender, clear-lavender, clear-lavender, mirrored-brown, mirrored-brown, mirrored-brown, mirrored-brown, mirrored-brown, shiny-bronze, shiny-bronze, shiny-bronze, shiny-bronze, shiny-bronze].
striped-blue = [dull-bronze, dotted-fuchsia, light-lavender, clear-turquoise].
dotted-olive = [dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-bronze, dotted-bronze, dotted-bronze, dotted-bronze, dotted-bronze, pale-yellow, pale-yellow, pale-yellow, pale-red, pale-red, pale-red, pale-red].
posh-silver = [pale-violet, pale-violet, pale-violet, plaid-salmon, posh-coral].
dotted-chartreuse = [bright-blue, bright-blue, bright-blue].
light-coral = [shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, pale-red, pale-red, muted-silver, bright-cyan, bright-cyan].
pale-brown = [light-aqua, light-aqua, light-aqua, light-aqua, light-aqua].
dotted-black = [plaid-purple, plaid-purple, mirrored-aqua, posh-beige, posh-beige, posh-beige, posh-beige, posh-beige].
posh-coral = [dark-aqua, dark-aqua, dark-aqua, pale-yellow, pale-yellow, plaid-blue, plaid-blue, plaid-blue, plaid-blue, plaid-blue, dim-aqua, dim-aqua, dim-aqua, dim-aqua].
shiny-gray = [bright-gold, muted-bronze, striped-green, striped-green, striped-green, striped-green, striped-green, shiny-teal, shiny-teal, shiny-teal, shiny-teal, shiny-teal].
drab-orange = [plaid-salmon, plaid-salmon, plaid-salmon, plaid-salmon, plaid-salmon, vibrant-beige, vibrant-beige].
plaid-yellow = [clear-teal, clear-teal, clear-teal, clear-teal, bright-red, bright-red].
striped-violet = [mirrored-fuchsia, mirrored-fuchsia, mirrored-fuchsia, mirrored-fuchsia, vibrant-white, vibrant-white, vibrant-white, vibrant-white, dim-teal, dim-teal, dim-teal].
dim-aqua = [muted-fuchsia, dull-tan].
light-orange = [bright-red, bright-red, dark-white, dark-white, dark-white, dark-white, dim-chartreuse, faded-fuchsia, faded-fuchsia, faded-fuchsia, faded-fuchsia, faded-fuchsia].
faded-salmon = [wavy-gray, wavy-gray, wavy-gray, wavy-gray, wavy-gray].
shiny-yellow = [vibrant-plum, vibrant-plum, dim-teal, dim-teal, dim-teal, plaid-tan, posh-plum, posh-plum, posh-plum, posh-plum, posh-plum].
vibrant-beige = [wavy-lavender, wavy-lavender, posh-chartreuse, posh-chartreuse, posh-chartreuse, posh-chartreuse, pale-teal, pale-teal, pale-teal, wavy-lime, wavy-lime, wavy-lime, wavy-lime, wavy-lime].
light-fuchsia = [clear-brown, clear-brown, clear-brown, bright-lavender, bright-lavender, bright-lavender].
pale-magenta = [posh-silver, posh-silver, posh-silver, posh-silver].
dark-maroon = [drab-turquoise, drab-turquoise, drab-turquoise].
faded-beige = [vibrant-white, drab-red, drab-red, drab-red, drab-red, drab-lavender].
bright-bronze = [pale-bronze, muted-silver, muted-silver, muted-silver, striped-coral, striped-coral, clear-gray, clear-gray, clear-gray].
light-silver = [dotted-lavender, dotted-lavender, dotted-lavender, wavy-lavender, wavy-lavender].
muted-salmon = [drab-tan, drab-tan, wavy-tomato, wavy-tomato, wavy-tomato, wavy-tomato, wavy-tomato].
bright-black = [plaid-tan, plaid-tan, plaid-tan, plaid-tan, plaid-tan].
dim-chartreuse = [muted-gold, muted-gold, muted-gold, muted-gold, muted-gold, bright-blue, bright-blue, bright-blue, bright-blue, bright-blue, faded-cyan, faded-cyan, faded-cyan, faded-cyan, faded-cyan].
shiny-white = [bright-tan, bright-tan, bright-tan, bright-tan].
bright-red = [dull-silver, dull-silver, dull-silver].
dark-aqua = [dull-red, dull-red].
drab-plum = [muted-brown, muted-brown, muted-brown, muted-brown, muted-plum, muted-plum, muted-plum, muted-plum, muted-plum].
muted-yellow = [light-purple, light-purple, light-purple, light-purple, light-purple, dotted-silver, dotted-silver, dotted-silver, faded-turquoise, faded-turquoise, faded-turquoise].
light-violet = [pale-red, dim-silver, dim-silver, dim-silver, dim-silver, mirrored-bronze, mirrored-bronze].
pale-lime = [bright-lavender, bright-lavender, bright-lavender, bright-lavender].
pale-tan = [striped-green, striped-green, striped-green, striped-green, dotted-chartreuse, dotted-chartreuse].
dim-green = [light-lime, shiny-beige].
mirrored-gold = [mirrored-white, mirrored-white, mirrored-white, mirrored-white].
dim-silver = [pale-coral, pale-coral, pale-coral, pale-coral, pale-coral, wavy-coral, wavy-coral, wavy-coral].
dull-aqua = [posh-indigo, posh-indigo, posh-indigo, dotted-coral, dotted-coral, dotted-coral, dotted-coral, dotted-coral, dark-salmon, striped-crimson, striped-crimson, striped-crimson].
posh-yellow = [dark-bronze, mirrored-white, mirrored-white, light-crimson, light-crimson].
mirrored-magenta = [bright-violet, drab-lavender, drab-lavender, pale-violet, pale-violet, pale-violet, plaid-salmon, plaid-salmon].
shiny-chartreuse = [dotted-purple, dotted-purple, wavy-red, wavy-red, wavy-red, wavy-red, wavy-red, plaid-beige, plaid-beige, plaid-beige].
light-black = [dark-chartreuse, faded-tomato, faded-tomato, faded-tomato].
clear-plum = [vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, dim-coral, dim-coral, dim-coral, mirrored-brown, mirrored-brown, mirrored-brown, mirrored-brown, faded-black].
pale-violet = [dull-tan, dull-tan].
bright-fuchsia = [dull-orange, dull-orange, dull-orange, dull-orange].
dotted-teal = [bright-red, bright-red, bright-red, bright-red, bright-red, wavy-red, wavy-red, wavy-red, dull-coral, clear-plum, clear-plum, clear-plum].
dotted-blue = [wavy-beige, wavy-beige, muted-purple, muted-purple, muted-purple].
muted-gray = [faded-aqua, faded-aqua, faded-aqua, shiny-olive, clear-salmon, clear-salmon, clear-salmon, clear-salmon, clear-salmon, vibrant-violet].
dull-beige = [wavy-lavender, dark-bronze, dark-bronze, dark-bronze, dark-bronze, dull-tan, dull-tan, dull-tan, dull-tan, dull-tan].
drab-turquoise = [posh-gray, posh-gray, posh-gray, drab-red, drab-red, drab-red, drab-red, drab-red].
vibrant-yellow = [shiny-aqua, shiny-aqua, light-chartreuse, light-chartreuse, light-chartreuse, light-chartreuse].
posh-brown = [bright-green, bright-green, bright-green, posh-lavender, posh-lavender, posh-lavender, posh-lavender, posh-lavender].
faded-gold = [vibrant-maroon, vibrant-maroon, vibrant-maroon, vibrant-maroon, dotted-purple, dotted-purple, dotted-purple, dotted-purple].
dotted-turquoise = [clear-plum, clear-plum, clear-plum, clear-plum, clear-plum, muted-gold, muted-gold, muted-gold, dark-violet, dark-violet, dark-violet, dark-violet].
dotted-tan = [dim-aqua, dim-aqua, dim-aqua, dim-aqua, dim-aqua, striped-violet, striped-violet, striped-violet, striped-violet].
posh-crimson = [striped-blue, striped-blue, striped-blue, striped-blue, dull-magenta, dull-magenta, dull-magenta, dull-magenta, dull-magenta, bright-coral, bright-coral].
muted-white = [dull-olive, dull-olive, dull-olive, dull-olive, dull-olive].
vibrant-teal = [dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, striped-tan, drab-tan].
dotted-yellow = [plaid-turquoise, plaid-turquoise, plaid-turquoise, posh-yellow, posh-yellow, striped-blue, striped-blue, striped-blue, striped-blue, posh-black, posh-black, posh-black, posh-black, posh-black].
posh-magenta = [mirrored-black, mirrored-black, mirrored-black, mirrored-black, mirrored-black].
dotted-green = [dim-crimson, dim-crimson, dim-crimson, dim-crimson, shiny-lavender, bright-salmon, bright-salmon, bright-salmon, bright-salmon, plaid-gray].
bright-green = [bright-aqua, bright-aqua, bright-aqua, dull-maroon, dull-maroon, dull-maroon, dark-brown, dark-brown, dark-brown, dark-brown].
dark-gray = [muted-purple, muted-purple, muted-purple, muted-purple, muted-purple, striped-blue, striped-blue, faded-lavender, faded-lavender, faded-lavender, faded-lavender].
bright-crimson = [striped-olive, striped-olive, muted-blue, muted-blue, muted-blue].
muted-cyan = [shiny-tomato, shiny-tomato, shiny-tomato].
light-yellow = [striped-red, striped-red, shiny-crimson, shiny-crimson, shiny-crimson, shiny-crimson].
pale-aqua = [shiny-yellow, shiny-yellow, shiny-yellow, shiny-yellow, shiny-yellow, dark-lavender, dark-lavender, dark-lavender, posh-white, posh-white, posh-white].
clear-red = [dotted-silver, dull-teal, faded-maroon, dotted-salmon].
pale-red = [faded-gray, faded-gray].
dotted-maroon = [posh-aqua, posh-aqua, posh-aqua, posh-aqua, posh-aqua, dull-silver, dull-silver, dull-silver].
dull-blue = [light-crimson, light-crimson, light-crimson, light-crimson, light-lime, light-lime, light-lime, dark-orange, light-indigo, light-indigo, light-indigo, light-indigo, light-indigo].
posh-turquoise = [muted-gold, striped-lavender, striped-lavender, striped-lavender, striped-lavender, striped-lavender, dull-salmon, dull-salmon, dull-salmon, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse].
striped-magenta = [posh-silver, dark-brown, dark-brown, dark-brown, dark-brown, dark-brown].
pale-blue = [muted-gold, muted-gold, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, light-lavender].
vibrant-violet = [bright-red, bright-red, bright-red, bright-red, bright-red].
faded-fuchsia = [light-lime, light-lime, bright-lime, bright-lime, bright-lime, bright-lime, pale-violet, pale-violet, pale-violet].
shiny-coral = [clear-plum, muted-chartreuse, muted-chartreuse, muted-chartreuse, muted-chartreuse, muted-chartreuse, muted-violet, striped-yellow, striped-yellow, striped-yellow, striped-yellow, striped-yellow].
pale-olive = [plaid-lime, plaid-lime, plaid-lime, plaid-lime, posh-salmon].
wavy-tan = [faded-gray, faded-gray, faded-gray].
faded-chartreuse = [dim-coral, dim-coral, dim-coral, mirrored-bronze, posh-bronze, posh-bronze, posh-bronze].
mirrored-brown = [faded-violet, dull-maroon, dull-maroon, dull-maroon, dull-maroon, dotted-magenta, dotted-magenta, dotted-magenta, dotted-magenta, dotted-magenta].
clear-white = [muted-magenta, muted-magenta, muted-magenta, muted-magenta, muted-magenta, dull-magenta, dull-magenta, dull-magenta, dull-magenta, pale-plum, pale-plum, pale-plum, drab-indigo, drab-indigo, drab-indigo, drab-indigo].
drab-maroon = [clear-beige, clear-beige, wavy-beige, wavy-beige, wavy-beige, faded-purple, faded-purple, faded-purple, faded-purple, faded-purple].
striped-silver = [drab-tomato, drab-tomato, drab-tomato].
faded-plum = [clear-teal, bright-aqua, bright-aqua, bright-aqua].
plaid-violet = [drab-violet, drab-violet, muted-turquoise, muted-turquoise, muted-turquoise, muted-turquoise, muted-indigo, muted-indigo, muted-indigo, muted-indigo, muted-indigo].
clear-black = [muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-coral, light-black, light-black].
vibrant-maroon = [dark-lavender, pale-crimson, bright-indigo, bright-indigo, bright-indigo, bright-indigo, mirrored-maroon, mirrored-maroon, mirrored-maroon, mirrored-maroon, mirrored-maroon].
drab-indigo = [dim-coral, dim-coral, drab-green, shiny-lavender, shiny-lavender].
drab-olive = [dark-aqua, dark-aqua, striped-brown, striped-brown, striped-brown, striped-brown].
dull-crimson = [dull-cyan, dull-cyan, dull-cyan].
wavy-teal = [striped-orange, striped-orange, striped-orange, striped-orange, drab-cyan, drab-cyan].
dark-red = [dull-maroon, dull-maroon, muted-plum, muted-plum, muted-plum, muted-plum, dull-plum, dull-plum, dull-plum, dull-plum].
striped-salmon = [bright-red, bright-red, bright-red, light-aqua, wavy-gold, wavy-gold, wavy-gold, wavy-gold].
mirrored-tan = [dotted-olive, dotted-olive, dotted-olive, dotted-olive, dotted-olive, dim-tomato, dim-tomato, mirrored-tomato, mirrored-tomato, clear-teal, clear-teal, clear-teal, clear-teal].
striped-white = [pale-coral, pale-coral, shiny-green, shiny-green].
shiny-tomato = [pale-coral, pale-coral, pale-coral, pale-coral, pale-coral, dull-beige, dull-beige, dull-beige, dull-beige, dull-beige].
vibrant-indigo = [dim-black, dim-black, dim-blue, dim-blue, dim-blue, dim-blue, dim-white, dim-white, dim-white].
wavy-lavender = [faded-bronze, faded-bronze, faded-bronze, faded-bronze, muted-red, muted-red, muted-red, muted-red, light-lime, light-lime, light-lime, muted-gold, muted-gold, muted-gold, muted-gold].
shiny-turquoise = [dull-red, dull-red, faded-gray, faded-gray, faded-gray, faded-gray, faded-gray, muted-turquoise].
shiny-lavender = [bright-aqua, bright-aqua, bright-aqua, bright-aqua, bright-aqua].
posh-tan = [shiny-yellow, drab-magenta, drab-magenta, drab-magenta].
light-green = [bright-red, bright-red, bright-red, bright-red, vibrant-coral].
drab-black = [faded-tomato, faded-tomato, faded-tomato, faded-tomato, faded-tomato, dotted-chartreuse, dotted-chartreuse, dotted-chartreuse].
clear-chartreuse = [wavy-bronze, wavy-bronze, wavy-bronze, plaid-purple, plaid-purple, plaid-purple, plaid-purple, dark-orange, dark-orange, dark-orange].
dull-black = [wavy-teal, light-lavender, light-lavender, light-lavender, striped-indigo, striped-indigo].
wavy-black = [clear-orange, clear-orange, muted-purple, muted-purple, muted-purple, muted-purple].
pale-plum = [bright-coral, drab-tan, plaid-fuchsia, dotted-fuchsia].
dotted-violet = [bright-black, bright-black, bright-black].
posh-red = [bright-black, bright-black, bright-black].
plaid-lime = [posh-beige, posh-beige, posh-beige, posh-beige, posh-beige, dotted-turquoise].
wavy-aqua = [dark-yellow, drab-indigo, drab-indigo, drab-indigo].
dim-magenta = [dark-violet, dark-violet, dark-violet].
drab-aqua = [posh-orange, posh-orange, posh-orange, posh-orange, posh-orange, dark-silver, plaid-purple, plaid-purple, plaid-purple, plaid-purple, wavy-teal, wavy-teal].
dull-brown = [light-lime, light-lime, light-lime, light-lime].
striped-orange = [light-crimson, light-crimson, light-crimson, light-crimson, light-crimson, muted-tan, muted-tan, muted-tan, dotted-coral, dotted-coral, dotted-coral, dotted-coral, dotted-coral, plaid-blue, plaid-blue, plaid-blue].
muted-brown = [posh-blue, dotted-magenta, dotted-magenta, dotted-magenta, dotted-magenta, dull-coral, dull-coral, dull-coral].
faded-blue = [striped-black, striped-black, striped-black, striped-black, striped-black, vibrant-yellow].
plaid-indigo = [dark-brown, dark-brown, dark-brown, light-purple, light-purple, light-purple, light-purple, light-purple, light-aqua, light-aqua, light-aqua, light-aqua, light-green, light-green, light-green].
plaid-turquoise = [dotted-teal, dotted-teal, dotted-teal, dotted-teal, dotted-teal].
light-turquoise = [dull-salmon, dull-salmon, dotted-tan, dotted-tan, dotted-tan, dotted-tan, dotted-tan].
dim-purple = [muted-white, muted-white, muted-white, muted-white, drab-purple, drab-purple, drab-purple, drab-purple, drab-purple].
pale-coral = [posh-gray, posh-gray, posh-gray, posh-gray, posh-gray].
clear-lime = [dim-magenta, dim-magenta, dim-magenta, plaid-tomato, plaid-tomato, plaid-tomato, drab-magenta, shiny-purple, shiny-purple, shiny-purple].
dim-black = [clear-gold, clear-gold, clear-gold, muted-violet, muted-violet, muted-violet, muted-violet].
light-maroon = [muted-yellow, muted-yellow, muted-yellow, muted-yellow, pale-cyan, mirrored-turquoise, mirrored-turquoise, dull-lavender, dull-lavender, dull-lavender, dull-lavender].
clear-magenta = [shiny-magenta, shiny-magenta, muted-chartreuse, muted-chartreuse].
striped-bronze = [clear-tan, clear-tan, clear-tan, clear-tan, clear-tan, drab-lavender, pale-crimson, pale-crimson].
dark-salmon = [vibrant-plum, drab-tan, drab-tan, drab-tan, drab-tan, drab-tan, drab-coral, drab-coral, drab-coral, drab-coral, dull-tan, dull-tan, dull-tan, dull-tan].
vibrant-salmon = [muted-olive, muted-olive].
dim-gold = [dim-olive, dim-olive, plaid-olive, plaid-olive, plaid-olive, plaid-olive, plaid-olive, posh-orange, posh-orange].
wavy-chartreuse = [shiny-yellow, shiny-yellow, shiny-yellow, shiny-yellow, vibrant-blue, vibrant-blue, vibrant-blue, vibrant-blue].
vibrant-brown = [striped-brown, striped-brown, striped-brown, muted-red, muted-red, muted-red, muted-red, shiny-indigo, shiny-indigo].
plaid-maroon = [muted-teal, muted-teal, pale-yellow, pale-yellow, bright-beige, bright-beige, striped-yellow, striped-yellow, striped-yellow, striped-yellow, striped-yellow].
dim-indigo = [dull-tomato, dull-tomato, dull-tomato, dull-tomato, clear-cyan, clear-cyan, clear-cyan, clear-cyan, shiny-salmon, shiny-salmon, bright-aqua].
muted-red = [dull-tan, dull-tan, dull-tan, dull-magenta, dull-magenta, dull-magenta, dull-magenta, bright-aqua].
posh-beige = [shiny-black, shiny-black, shiny-black, shiny-black, shiny-black, dotted-magenta, dotted-magenta, dotted-magenta, drab-blue, drab-blue, drab-blue, muted-coral, muted-coral].
pale-fuchsia = [dark-brown, dark-brown, dark-brown, posh-gold, posh-gold, posh-gold, posh-gold, posh-gold].
dark-bronze = [dim-green, posh-chartreuse, posh-chartreuse, posh-chartreuse, posh-chartreuse, posh-chartreuse].
dim-coral = [dull-coral, dull-coral, dull-coral, striped-brown, striped-brown, striped-brown].
drab-crimson = [dark-bronze, dark-bronze, shiny-indigo, shiny-indigo, shiny-indigo, shiny-indigo, dull-tan, dull-tan, dull-tan].
bright-indigo = [bright-blue, bright-blue, bright-blue].
pale-yellow = [dim-aqua, dim-aqua, dim-aqua, dim-aqua, dim-aqua, vibrant-brown, vibrant-tan, vibrant-tan, wavy-lavender, wavy-lavender, wavy-lavender].
drab-salmon = [dotted-indigo, muted-chartreuse, muted-chartreuse, muted-chartreuse, dark-olive, dark-olive, dark-olive, dark-olive, dark-olive].
muted-orange = [faded-lime, faded-lime, faded-lime, faded-lime, dull-coral, dull-coral, vibrant-magenta, vibrant-magenta, vibrant-magenta, vibrant-magenta, vibrant-magenta, dull-magenta, dull-magenta, dull-magenta, dull-magenta].
striped-gold = [dull-silver, dull-silver, bright-lavender, bright-lavender, bright-lavender, bright-lavender, bright-lavender, dim-teal, dim-teal, dim-teal, dim-teal, dim-teal, dark-coral, dark-coral, dark-coral, dark-coral, dark-coral].
posh-chartreuse = [dim-teal, dim-teal, dim-teal, light-aqua, light-aqua, light-aqua, light-aqua, light-aqua].
shiny-blue = [dull-tan, dull-tan, dull-tan, muted-magenta, muted-magenta, muted-magenta, muted-magenta, muted-magenta].
muted-silver = [wavy-blue, wavy-blue, wavy-blue, dim-teal, dim-teal, muted-bronze, muted-bronze, muted-bronze, muted-bronze, muted-bronze].
shiny-bronze = [light-green, vibrant-magenta, vibrant-magenta, vibrant-magenta, vibrant-magenta].
wavy-coral = [no-other].
shiny-orange = [muted-purple, muted-purple].
posh-teal = [clear-plum, clear-plum, clear-plum, clear-plum].
striped-turquoise = [muted-indigo, muted-indigo, muted-indigo].
dim-bronze = [shiny-silver, shiny-silver, light-silver, dim-indigo, dim-indigo, dim-tomato, dim-tomato, dim-tomato, dim-tomato].
plaid-white = [drab-turquoise, drab-turquoise, drab-turquoise, drab-turquoise].
wavy-indigo = [clear-gold, clear-gold, clear-gold, mirrored-bronze, mirrored-bronze, mirrored-bronze, mirrored-bronze, mirrored-bronze].
faded-teal = [mirrored-white, mirrored-white, mirrored-white, mirrored-white].
shiny-fuchsia = [drab-indigo, drab-indigo, drab-indigo].
dim-red = [clear-bronze, clear-bronze, clear-bronze].
dotted-brown = [wavy-maroon, wavy-maroon, wavy-maroon, wavy-maroon, drab-green, drab-green, drab-green, drab-green, drab-green, dark-purple, dark-purple, dark-purple].
dark-tomato = [vibrant-coral, vibrant-coral, vibrant-coral, dull-coral, dull-coral, dull-coral, dull-coral, dull-coral, drab-cyan, drab-cyan, posh-blue].
clear-teal = [dark-white, dark-white, dark-white].
dark-silver = [dark-cyan, dark-cyan, dark-cyan, plaid-salmon, plaid-salmon, plaid-salmon, plaid-salmon].
wavy-fuchsia = [bright-brown, bright-brown, bright-brown, bright-brown, bright-aqua, bright-aqua, bright-aqua, bright-aqua, light-orange, light-orange, light-orange, light-orange, light-orange].
light-bronze = [clear-plum, clear-plum, clear-plum, clear-plum].
striped-purple = [dim-indigo].
clear-tomato = [mirrored-tomato, mirrored-tomato, mirrored-tomato, mirrored-tomato, muted-indigo, muted-indigo, muted-indigo, striped-tan].
muted-turquoise = [faded-beige, faded-beige, faded-beige, faded-beige, faded-beige, clear-crimson, clear-crimson, clear-crimson, clear-crimson, bright-teal, bright-teal].
dull-cyan = [mirrored-aqua, mirrored-aqua, mirrored-aqua, mirrored-aqua, mirrored-aqua, shiny-aqua, shiny-aqua, light-black, light-black, light-black, bright-coral, bright-coral, bright-coral, bright-coral].
plaid-crimson = [mirrored-teal, mirrored-teal, dull-fuchsia, dull-fuchsia].
shiny-maroon = [posh-gold].
dim-white = [striped-brown, striped-brown, striped-brown, striped-brown, striped-brown, dull-magenta, dull-magenta, plaid-tan, plaid-tan, plaid-tan, plaid-tan, plaid-tan].
muted-green = [dull-magenta, dull-magenta, clear-cyan, clear-cyan, clear-cyan, clear-cyan, clear-cyan].
plaid-teal = [dark-tan, dark-tan, pale-lime, pale-lime, pale-lime].
dotted-lavender = [posh-aqua, posh-aqua, dull-cyan, dull-cyan, dull-cyan].
light-salmon = [dark-silver, dark-silver, dark-silver, dark-silver, dark-silver].
faded-white = [wavy-maroon, wavy-maroon, dull-cyan, dull-cyan, dull-cyan].
dull-tomato = [dim-aqua, dim-aqua, posh-lavender, posh-lavender, posh-lavender, posh-lavender, faded-red].
dark-olive = [clear-bronze, clear-bronze, clear-bronze, clear-bronze, clear-bronze, drab-plum, drab-plum].
pale-indigo = [mirrored-beige, mirrored-beige, wavy-turquoise, wavy-turquoise, wavy-turquoise, wavy-turquoise, wavy-turquoise, striped-green, striped-green, striped-green, striped-green, dotted-lavender, dotted-lavender].
plaid-purple = [light-lime].
clear-purple = [vibrant-white, vibrant-white, vibrant-white].
dark-yellow = [pale-olive, pale-olive, pale-cyan, pale-cyan, pale-cyan, pale-cyan, bright-teal, bright-teal, bright-teal, bright-teal, bright-teal].
muted-beige = [posh-lime, posh-lime, shiny-gray, shiny-gray, shiny-gray, shiny-gray, shiny-gray, dull-blue, dull-blue].
vibrant-orange = [posh-crimson, posh-crimson, posh-crimson, posh-crimson, posh-crimson, light-chartreuse, light-chartreuse, light-chartreuse, light-chartreuse].
light-magenta = [plaid-maroon, plaid-maroon, posh-beige, pale-salmon, pale-salmon, pale-salmon, pale-salmon, pale-salmon].
dotted-crimson = [dark-chartreuse, dark-chartreuse, dark-chartreuse, dark-chartreuse, dark-chartreuse].
striped-coral = [dim-aqua, dim-aqua].
striped-aqua = [posh-salmon, posh-salmon, posh-salmon, dull-red, dull-red, dull-red].
mirrored-salmon = [bright-red, bright-red, bright-red, bright-red, bright-red, light-green, light-green, clear-black, clear-black, clear-black, posh-brown, posh-brown, posh-brown, posh-brown, posh-brown].
posh-white = [drab-violet, drab-violet, drab-violet, drab-violet, dotted-silver, dotted-silver].
posh-blue = [dull-maroon, dull-maroon, dull-maroon, dull-maroon, vibrant-coral, vibrant-coral, vibrant-coral].
dim-orange = [dull-olive, dull-olive].
shiny-teal = [faded-tomato, muted-violet, muted-violet, muted-violet, muted-violet].
mirrored-maroon = [dull-blue, dull-blue, dull-blue].
dark-lavender = [drab-red, shiny-indigo, shiny-indigo, shiny-indigo, faded-beige, faded-beige, faded-beige, faded-beige, drab-turquoise].
shiny-olive = [dark-violet, dark-violet, dark-violet, striped-gold, mirrored-lime, mirrored-lime].
bright-violet = [wavy-bronze, wavy-bronze, drab-olive, drab-olive, drab-olive, mirrored-olive, mirrored-olive, mirrored-olive, mirrored-olive, mirrored-olive, wavy-lavender, wavy-lavender].
clear-olive = [faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise].
mirrored-lavender = [light-white, light-purple, light-purple, light-purple, light-purple, wavy-lavender, wavy-lavender, wavy-lavender, shiny-lime, shiny-lime].
pale-turquoise = [dark-tan, dark-tan, dark-tan, dark-tan].
shiny-salmon = [shiny-gold, drab-turquoise, drab-turquoise, drab-turquoise, drab-turquoise, drab-turquoise].
vibrant-gray = [posh-brown, posh-brown, posh-brown].
dark-indigo = [mirrored-black, dull-beige, dull-beige, dull-beige, dull-beige, dull-beige, shiny-beige, shiny-beige, shiny-beige, shiny-beige, drab-lavender, drab-lavender, drab-lavender].
light-teal = [dark-olive, dark-olive, dark-olive, dark-olive, dark-olive, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, vibrant-chartreuse, plaid-salmon, plaid-salmon, plaid-salmon, light-yellow, light-yellow, light-yellow, light-yellow, light-yellow].
clear-violet = [light-crimson, light-crimson, light-crimson].
clear-tan = [striped-orange, striped-orange, striped-orange, wavy-lavender, wavy-lavender, wavy-lavender, wavy-lavender, striped-silver, striped-silver, striped-silver].
clear-bronze = [plaid-beige, plaid-beige].
clear-gray = [dotted-cyan, dotted-cyan, dotted-cyan, dotted-cyan, vibrant-plum, vibrant-plum, vibrant-plum, vibrant-plum].
drab-cyan = [light-aqua, drab-teal, bright-orange, bright-orange, bright-orange, dark-white, dark-white, dark-white].
plaid-beige = [dull-green, dull-green, dull-green].
wavy-gold = [shiny-olive, shiny-olive, shiny-olive, shiny-olive, bright-tan, bright-tan, bright-tan].
clear-aqua = [posh-chartreuse, posh-chartreuse, posh-chartreuse, drab-silver, drab-silver, drab-silver, drab-silver, clear-gray, clear-gray, clear-gray, clear-gray, clear-gray].
bright-chartreuse = [light-violet, light-violet, vibrant-gray, vibrant-gray, vibrant-gray].
plaid-black = [posh-gray, posh-gray].
light-beige = [dotted-olive, dotted-olive, dotted-olive, dotted-olive, dull-olive, dull-olive, dull-olive, dull-olive, dull-olive, faded-orange].
mirrored-teal = [mirrored-aqua, mirrored-aqua, mirrored-aqua, mirrored-aqua].
bright-magenta = [mirrored-magenta, bright-blue, bright-blue, bright-blue, vibrant-blue, drab-gold, drab-gold].
dim-maroon = [light-bronze, light-bronze, light-bronze, light-bronze, clear-violet, clear-violet, clear-violet, clear-violet, clear-violet].
light-lime = [plaid-indigo, plaid-indigo, plaid-indigo, plaid-indigo].
posh-lavender = [dark-brown, dark-brown, dark-brown, dark-brown].
clear-beige = [posh-silver, posh-silver, posh-silver, posh-silver, dull-coral, dull-coral, dull-coral, posh-gray, posh-gray].
drab-bronze = [plaid-maroon, plaid-maroon, plaid-maroon, plaid-maroon].
mirrored-purple = [dim-magenta, dim-magenta, dim-magenta].
dark-magenta = [faded-maroon, faded-maroon, faded-maroon, faded-maroon, drab-crimson, dotted-brown, dotted-brown, dotted-brown, dotted-brown, dotted-brown, bright-teal, bright-teal].
dim-brown = [muted-olive, muted-olive, muted-olive, drab-green, drab-green, drab-green, drab-green, drab-green, mirrored-olive].
dark-plum = [vibrant-tan, vibrant-tan].
bright-turquoise = [mirrored-aqua, clear-plum, clear-plum, clear-plum].
muted-black = [faded-cyan, faded-cyan, faded-cyan, faded-cyan, faded-cyan, pale-tan, pale-tan, pale-tan, pale-tan, pale-tan, dotted-chartreuse, dotted-chartreuse].
dotted-gray = [posh-plum, posh-plum, posh-plum].
vibrant-black = [vibrant-magenta, vibrant-magenta, faded-cyan, faded-cyan, faded-cyan, faded-cyan, faded-cyan].
mirrored-cyan = [clear-cyan, clear-cyan, light-aqua, light-aqua, light-aqua, light-aqua, drab-blue, drab-blue, drab-blue, drab-blue, drab-blue, drab-gold].
wavy-purple = [striped-magenta, striped-magenta, striped-magenta, striped-magenta, striped-magenta, clear-maroon, clear-maroon, clear-maroon, mirrored-green, pale-black].
drab-blue = [mirrored-lime, mirrored-lime, mirrored-lime, mirrored-blue].
clear-maroon = [bright-orange, bright-orange, bright-orange, bright-orange, bright-orange].
shiny-cyan = [clear-gray, clear-gray, pale-crimson, pale-crimson, pale-crimson, pale-crimson, pale-crimson].
pale-cyan = [wavy-turquoise, wavy-turquoise, wavy-salmon, wavy-salmon, wavy-salmon, wavy-salmon, wavy-salmon].
plaid-gold = [clear-lavender, bright-beige].
mirrored-lime = [dull-tan, dull-tan, shiny-beige, shiny-beige, shiny-beige].
drab-green = [vibrant-yellow].
dull-red = [plaid-blue, plaid-blue, plaid-blue, plaid-blue, plaid-blue, clear-brown, clear-brown, clear-brown, clear-brown, clear-brown, pale-salmon, pale-salmon, pale-salmon, dark-orange, dark-orange].
bright-beige = [dull-silver, dull-silver, dull-silver, dull-silver, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, vibrant-brown, drab-red, drab-red, drab-red, drab-red, pale-violet, pale-violet].
clear-silver = [drab-indigo, drab-indigo, drab-indigo, drab-indigo, clear-salmon, clear-salmon].
posh-bronze = [bright-indigo, bright-indigo, bright-indigo, bright-indigo, bright-indigo, dotted-purple, dotted-purple, dotted-purple, dotted-purple, dotted-purple, dark-violet, dark-orange, dark-orange].
posh-salmon = [bright-red, bright-red, bright-red, bright-red, bright-red, striped-green, striped-green, striped-green, dark-brown, dark-brown, dark-brown].
clear-cyan = [dark-chartreuse, dark-chartreuse, dark-chartreuse, dark-chartreuse, dark-chartreuse, bright-indigo, pale-yellow, pale-yellow, pale-yellow, pale-yellow, vibrant-coral, vibrant-coral].
mirrored-blue = [vibrant-white, vibrant-white].
mirrored-yellow = [dotted-gray, dotted-gray, dotted-gray, dotted-gray, dotted-gray, dull-maroon, dull-maroon, dull-maroon, dull-maroon, striped-violet, striped-violet, clear-tomato, clear-tomato, clear-tomato, clear-tomato, clear-tomato].
striped-teal = [clear-black, clear-black, pale-coral, pale-coral, pale-coral].
faded-orange = [dark-bronze, dark-bronze].
mirrored-indigo = [light-tomato, light-tomato, light-tomato, shiny-crimson, shiny-crimson].
pale-green = [light-chartreuse, light-chartreuse, light-chartreuse, light-chartreuse].
plaid-cyan = [plaid-fuchsia, plaid-fuchsia, plaid-fuchsia, plaid-fuchsia, shiny-teal, shiny-teal, dotted-fuchsia, dotted-fuchsia, dotted-fuchsia, dim-red, dim-red, dim-red].
muted-gold = [dull-tan, dull-tan, faded-bronze, dull-maroon, dull-maroon, dull-maroon, dull-maroon].
wavy-green = [pale-coral, pale-coral, pale-coral, pale-coral, pale-coral, dull-blue, drab-blue, drab-blue, drab-blue, drab-blue, striped-tan].
light-chartreuse = [striped-brown, striped-brown, striped-brown, striped-brown, plaid-purple, plaid-purple, plaid-purple, plaid-purple, plaid-purple, drab-cyan, drab-cyan, drab-cyan, drab-cyan, dull-plum, dull-plum, dull-plum].
dotted-cyan = [shiny-black, shiny-black, shiny-black, shiny-black].
light-purple = [no-other].
dotted-aqua = [light-gray, light-gray, light-gray, light-gray, light-purple, light-purple, mirrored-lime, mirrored-lime, mirrored-lime, mirrored-lime, mirrored-lime].
drab-gold = [bright-green, bright-green, bright-indigo, bright-indigo, bright-indigo, bright-indigo, bright-indigo].
posh-gray = [bright-orange, bright-orange, bright-orange, bright-orange, bright-orange, bright-blue, bright-blue, bright-blue, bright-blue, bright-blue].
striped-red = [drab-green, drab-green, drab-green, drab-green, clear-cyan].
dotted-bronze = [light-orange, light-orange, light-orange, light-orange, light-orange].
muted-plum = [bright-black, bright-black, dotted-tomato, dotted-tomato, dotted-tomato, vibrant-brown, vibrant-brown].
mirrored-black = [plaid-chartreuse, plaid-chartreuse, plaid-chartreuse, shiny-indigo, shiny-indigo, shiny-beige, shiny-beige].
drab-lavender = [drab-cyan, drab-cyan, drab-cyan, drab-cyan, drab-cyan, muted-purple, wavy-red, drab-crimson, drab-crimson, drab-crimson].
vibrant-turquoise = [shiny-beige, shiny-beige, shiny-beige, striped-brown, striped-brown, striped-brown, dim-teal, dim-teal, dim-teal, dim-teal, dim-teal].
muted-tan = [plaid-purple, shiny-beige, shiny-beige, shiny-beige, drab-gold].
pale-beige = [bright-silver, bright-silver, bright-silver, bright-silver, bright-silver].
wavy-olive = [dotted-turquoise, dotted-turquoise, dotted-turquoise, dotted-turquoise, dull-silver, dull-silver, dull-silver, dull-silver, bright-gold].
dim-olive = [light-lavender, light-lavender, light-lavender, light-lavender, light-lavender, shiny-tomato, shiny-tomato, shiny-tomato, shiny-tomato, clear-cyan, clear-cyan, clear-cyan, clear-cyan].
wavy-salmon = [bright-aqua, bright-aqua, bright-aqua, bright-aqua].
dotted-gold = [shiny-red, shiny-red, shiny-red, dull-fuchsia, dull-fuchsia, dull-fuchsia].
shiny-violet = [dotted-tomato, dotted-tomato, dotted-tomato, drab-coral].
striped-plum = [drab-beige, drab-beige, drab-beige, drab-beige, clear-tan, clear-tan, clear-tan, light-aqua, light-aqua, light-aqua, light-aqua, light-aqua, shiny-fuchsia].
clear-lavender = [bright-aqua, bright-aqua, dull-silver, dull-silver, dull-silver, bright-green, bright-green, bright-green, bright-orange, bright-orange].
faded-maroon = [dark-indigo, dark-indigo, dark-indigo, dark-indigo, dark-indigo, posh-fuchsia].
vibrant-red = [striped-fuchsia, striped-fuchsia, striped-fuchsia, striped-fuchsia, drab-orange, drab-orange, drab-orange, clear-brown, plaid-turquoise].
dull-coral = [dim-teal, dim-teal, faded-bronze, faded-bronze, faded-bronze].
pale-salmon = [dull-magenta, dull-magenta, dull-magenta, light-crimson].
dotted-magenta = [dull-maroon, dull-maroon, dull-maroon, dull-maroon, bright-lime, bright-lime, plaid-indigo, plaid-indigo, plaid-indigo, plaid-indigo, faded-cyan, faded-cyan, faded-cyan, faded-cyan].
wavy-gray = [muted-gray, muted-gray, muted-gray, muted-gray, shiny-magenta, shiny-magenta, shiny-magenta, posh-teal].
light-red = [shiny-chartreuse, shiny-chartreuse, shiny-chartreuse, shiny-chartreuse].
dim-blue = [vibrant-orange, vibrant-orange, vibrant-orange, vibrant-orange].
muted-bronze = [mirrored-aqua, mirrored-aqua, mirrored-aqua, mirrored-aqua, mirrored-aqua, dim-green, dim-green, dim-green, dim-green].
drab-lime = [drab-cyan, pale-crimson, pale-crimson, pale-crimson, bright-green, bright-green, bright-green, bright-green, drab-lavender, drab-lavender, drab-lavender].
light-white = [bright-green, bright-green, bright-green, bright-green, bright-green].
bright-teal = [shiny-brown, shiny-brown, shiny-brown, shiny-brown, dark-silver, dark-silver, dark-silver, dark-silver].
striped-beige = [shiny-magenta, shiny-magenta].
wavy-magenta = [pale-bronze, pale-bronze, pale-bronze, pale-bronze, pale-bronze, pale-plum, pale-plum, pale-plum, pale-plum, pale-plum, muted-silver, muted-silver, muted-silver].
dark-orange = [drab-tomato, striped-brown, striped-brown, striped-brown, dim-teal, bright-beige, bright-beige, bright-beige, bright-beige, bright-beige].
striped-indigo = [vibrant-gold, shiny-green].
clear-coral = [shiny-gray, shiny-gray].
faded-yellow = [faded-gold, faded-gold, faded-gold, faded-gold, bright-turquoise, bright-turquoise, dark-silver, dark-silver, dark-silver, dark-silver, dark-silver, wavy-coral, wavy-coral, wavy-coral].
dim-plum = [clear-purple, light-brown, light-brown, light-brown, light-brown].
mirrored-turquoise = [wavy-indigo, wavy-indigo, wavy-indigo, wavy-indigo, wavy-indigo, dark-fuchsia, dark-fuchsia, dark-fuchsia, plaid-white, plaid-white, plaid-white, plaid-white, plaid-white, dim-turquoise, dim-turquoise].
posh-black = [striped-black, striped-black, dim-teal, dim-teal, dim-teal, dim-teal, dim-teal, bright-silver, bright-silver, bright-silver, posh-beige, posh-beige, posh-beige, posh-beige, posh-beige].
dotted-fuchsia = [faded-turquoise, shiny-lavender, shiny-lavender, posh-salmon, posh-salmon, posh-salmon, posh-salmon, clear-olive].
faded-lavender = [striped-yellow, striped-yellow, posh-lavender].
dim-lime = [wavy-gray, wavy-gray, clear-gray, clear-gray, clear-gray, clear-gray, clear-gray].
vibrant-bronze = [drab-tomato, drab-tomato, drab-tomato, bright-tan, bright-tan, bright-tan, bright-tan, bright-tan].
dull-plum = [bright-red, bright-red, bright-red, bright-red, bright-red, dull-magenta, dull-magenta, dull-magenta, dull-magenta].
dim-teal = [light-purple, light-purple, light-purple, light-purple, plaid-lavender, plaid-lavender, plaid-lavender, plaid-lavender, dull-magenta].
dull-yellow = [vibrant-orange, vibrant-orange, vibrant-orange, vibrant-orange, dark-tomato, pale-tan, pale-tan, pale-tan, pale-tan, pale-tan].
dull-green = [bright-blue, bright-blue, dull-red, dull-red, dull-red, dull-red, dull-red].
light-crimson = [dull-maroon, dull-maroon, dull-maroon, dull-maroon, dull-maroon, muted-gold, muted-gold, muted-gold, muted-gold].
dark-black = [dim-silver, plaid-magenta, plaid-magenta, plaid-magenta].
bright-lavender = [muted-fuchsia, muted-fuchsia, muted-fuchsia, muted-fuchsia].
drab-coral = [shiny-chartreuse, shiny-chartreuse, shiny-chartreuse, shiny-chartreuse, posh-yellow, posh-yellow, posh-yellow, wavy-indigo, wavy-indigo, wavy-indigo].
mirrored-crimson = [posh-maroon, posh-maroon, posh-maroon, striped-olive, striped-olive, striped-olive, striped-olive, striped-olive, mirrored-magenta, mirrored-magenta, mirrored-magenta].
muted-coral = [wavy-violet, wavy-violet, wavy-violet, dotted-chartreuse, shiny-beige].
vibrant-gold = [dull-orange, dull-orange, clear-chartreuse].
wavy-orange = [dark-bronze, dark-bronze, dark-bronze, dark-bronze, dark-bronze].
mirrored-white = [clear-gold, clear-gold, clear-gold, clear-gold, clear-gold, drab-tomato, drab-tomato, drab-tomato, dotted-bronze, dotted-bronze, dotted-bronze, dotted-bronze, striped-orange, striped-orange, striped-orange].
clear-gold = [drab-indigo, drab-indigo, drab-indigo, wavy-violet, wavy-violet, wavy-violet, wavy-violet, shiny-salmon, shiny-salmon, light-brown, light-brown, light-brown, light-brown].
shiny-magenta = [drab-silver, drab-silver, drab-silver, drab-silver, drab-silver, muted-gold, muted-gold].
dim-violet = [posh-lime, shiny-orange, shiny-orange, shiny-orange, shiny-orange, posh-chartreuse, posh-chartreuse].
striped-olive = [plaid-indigo, plaid-indigo, plaid-indigo, plaid-indigo, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, clear-lavender, clear-lavender, clear-lavender, clear-lavender].
plaid-gray = [shiny-gold, shiny-gold, shiny-gold, dull-coral, dull-coral].
clear-crimson = [shiny-aqua, shiny-aqua, shiny-aqua, shiny-aqua, light-crimson, light-crimson, light-crimson, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse, dim-chartreuse].
drab-silver = [dim-teal, faded-cyan, faded-cyan, faded-cyan, shiny-indigo].
mirrored-green = [dotted-lime, dotted-lime, dotted-lime, dotted-lime, dotted-lime, pale-cyan, pale-cyan, pale-cyan, pale-cyan].
bright-aqua = [no-other].
bright-plum = [dim-aqua, dim-aqua, dim-aqua, dim-aqua, dull-crimson, dull-crimson, wavy-maroon].
vibrant-lavender = [plaid-tan, vibrant-brown, vibrant-brown, vibrant-brown, drab-gold, drab-gold, drab-gold, faded-red, faded-red, faded-red, faded-red].
pale-white = [bright-brown, bright-brown, bright-brown, mirrored-beige, mirrored-beige, mirrored-beige, mirrored-beige].
plaid-lavender = [dull-magenta, dull-silver, dull-silver, shiny-indigo].
bright-salmon = [striped-coral, plaid-lavender, plaid-lavender, plaid-lavender, plaid-lavender, muted-red, drab-red].
plaid-olive = [faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise, faded-turquoise, dim-green, dim-green, dim-green, dim-green, striped-beige, striped-beige].
wavy-plum = [clear-lavender, faded-brown, faded-brown].
clear-fuchsia = [muted-bronze].
wavy-turquoise = [shiny-lime, shiny-lime, shiny-lime, shiny-lime, shiny-lime, drab-olive, dim-white, dim-white, dim-white, dim-white, dotted-gray].
vibrant-aqua = [faded-lavender, faded-lavender].
dotted-white = [muted-crimson, muted-crimson, muted-crimson, mirrored-white, mirrored-white, mirrored-white, mirrored-white, mirrored-white, mirrored-fuchsia].
bright-purple = [dotted-chartreuse, dotted-chartreuse, posh-cyan, posh-cyan, posh-cyan, posh-cyan, bright-plum, bright-plum, bright-plum].
light-aqua = [plaid-lavender, wavy-coral, wavy-coral, wavy-coral, shiny-indigo, shiny-indigo, shiny-indigo, shiny-indigo, shiny-indigo].
drab-yellow = [shiny-teal, shiny-teal, shiny-teal, shiny-teal, dotted-green, dotted-green, vibrant-silver, vibrant-silver, vibrant-silver, vibrant-silver, vibrant-silver, dotted-turquoise, dotted-turquoise, dotted-turquoise].
mirrored-olive = [dull-plum].
light-olive = [shiny-coral, drab-white, drab-white, drab-white, drab-white, dim-turquoise, dim-turquoise, dim-turquoise, dull-gold, dull-gold, dull-gold, dull-gold].
shiny-indigo = [no-other].
dull-gold = [dark-indigo, dark-indigo, dark-indigo].
bright-tomato = [muted-blue, muted-blue, muted-blue, muted-blue, muted-blue].
faded-purple = [bright-orange, bright-orange, bright-orange, bright-orange, faded-violet, faded-violet].
drab-magenta = [wavy-lavender, wavy-lavender, wavy-lavender, drab-cyan, drab-cyan, clear-beige, clear-beige, bright-indigo, bright-indigo, bright-indigo, bright-indigo].
striped-lime = [light-tan, light-tan, light-tan, light-tan].
light-gold = [pale-plum, pale-plum].
striped-black = [plaid-salmon, plaid-beige, plaid-beige, dotted-teal, dotted-teal, dotted-teal, dotted-teal, posh-chartreuse, posh-chartreuse].
faded-tomato = [striped-yellow, striped-yellow, muted-red, muted-red, muted-red, muted-red].
dull-fuchsia = [dotted-olive, dotted-olive, dotted-olive, dotted-olive, dotted-olive, muted-purple, muted-purple].
pale-purple = [posh-silver, posh-silver, posh-silver, posh-silver, wavy-yellow, wavy-yellow, wavy-yellow, wavy-yellow].
bright-olive = [shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, shiny-fuchsia, dull-crimson, dull-crimson, dull-crimson, dull-crimson, dull-crimson, drab-red, drab-red, drab-red, drab-red, drab-red, posh-turquoise, posh-turquoise, posh-turquoise, posh-turquoise, posh-turquoise].
vibrant-fuchsia = [vibrant-beige, shiny-magenta, shiny-magenta, shiny-magenta, shiny-magenta, shiny-magenta].
faded-turquoise = [light-lime, light-lime, light-lime, light-lime, light-lime, dark-white, dark-white, dark-white, dark-white].
plaid-orange = [vibrant-coral, vibrant-coral, vibrant-coral, vibrant-coral, vibrant-coral, light-crimson, light-crimson, light-crimson, light-crimson, plaid-chartreuse, plaid-chartreuse, plaid-chartreuse, plaid-chartreuse, dull-green].
posh-indigo = [wavy-green, wavy-green, wavy-green, shiny-orange, shiny-orange, faded-violet, faded-violet, faded-violet, faded-violet, faded-violet, dotted-coral, dotted-coral].
mirrored-red = [mirrored-olive, mirrored-olive, mirrored-olive, mirrored-olive, dark-silver, dull-red].
dim-salmon = [striped-salmon, faded-gray, faded-gray, faded-gray, faded-gray, faded-gray].
dim-cyan = [wavy-olive, wavy-olive, wavy-olive, drab-purple, drab-purple, drab-purple, drab-purple, drab-purple, mirrored-bronze, mirrored-bronze, mirrored-bronze].
light-blue = [striped-bronze, striped-bronze, dull-white, dull-white, dull-white, dull-white, posh-bronze].
dull-turquoise = [striped-red, striped-red, striped-red, striped-red, light-lavender, plaid-bronze, plaid-bronze, plaid-bronze, plaid-bronze, plaid-bronze, mirrored-brown].
vibrant-coral = [bright-orange].
striped-cyan = [dark-white, dark-white, drab-red, drab-red, drab-red, drab-red, plaid-salmon, plaid-salmon].
muted-tomato = [drab-red, drab-red, drab-red, drab-red, vibrant-silver, vibrant-silver, vibrant-silver, clear-fuchsia, clear-fuchsia, clear-fuchsia, clear-fuchsia, wavy-white, wavy-white, wavy-white].
dotted-red = [light-blue].
dark-beige = [posh-lime, posh-lime, striped-black, striped-black, striped-black].
dark-cyan = [dim-chartreuse, shiny-beige, shiny-beige, dotted-magenta, dotted-magenta, dotted-magenta, dotted-magenta, light-chartreuse, light-chartreuse, light-chartreuse, light-chartreuse].
dull-lime = [muted-chartreuse, muted-chartreuse, muted-chartreuse].
light-brown = [mirrored-brown, mirrored-brown, mirrored-brown].
vibrant-magenta = [dim-green].
shiny-brown = [bright-brown, bright-brown, bright-brown, bright-brown, bright-brown, faded-cyan, faded-cyan, faded-cyan, clear-tan, clear-tan, clear-tan, clear-tan, clear-tan, plaid-maroon, plaid-maroon].
drab-purple = [shiny-indigo, striped-yellow, striped-yellow, striped-yellow, striped-yellow].
